import type { GetStaticProps, NextPage } from "next";
import type { NextApiRequest, NextApiResponse } from "next";
import { groq } from "next-sanity";
import { sanityClient } from "../sanity";
// import { Experience } from "../typings";
import Image from "next/image";
import Head from "next/head";
import Header from "../components/header/Header";
import Hero from "../components/hero/Hero";
import gradient from "../public/bg-grdaient.png";
import About from "../components/about/About";
import ExperienceComponent from "../components/experience/ExperienceComponent";
import Skills from "../components/skills/Skills";
import Projects from "../components/projects/Projects";
import ContactMe from "../components/contact/ContactMe";
import { Experience, Skill, Social, Project, HomeInfo } from "../typings";
// import { GetStaticProps } from "next";
// import { fetchHomeInfo } from "../utils/fetchHomeInfo";
// import { fetchExperiences } from "../utils/fetchExperiences";
// import { fetchSocials } from "../utils/fetchSocials";
// import { fetchProjects } from "../utils/fetchProjects";
// import { fetchSkills } from "../utils/fetchSkills";
import { motion } from "framer-motion";

type Props = {
  // homeInfo: HomeInfo;
  experiences: Experience[];
  // skills: Skill[];
  // socials: Social[];
  // projects: Project[];
};

const Home = ({ experiences }: Props) => {
  return (
    <div className="scrollbar-thin scrollbar-track-neutral-100/20 scrollbar-thumb-neutral-100/50 bg-indigo-300 h-screen text-[#140e2c] snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0">
      <motion.video
        initial={{ opacity: 0 }}
        animate={{
          opacity: 1,
        }}
        transition={{
          duration: 0.4,
          delay: 0.3,
        }}
        autoPlay
        muted
        loop
        src={"/aguabg.mp4"}
        style={{
          height: "110vh",
          position: "absolute",
          width: "120vw",
          objectPosition: "top",
          objectFit: "cover",
          filter: "blur(10px)",
        }}
      />

      <Head>
        <title>Vals Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header socials={socials} /> */}

      <section id="hero" className="snap-start scroll-smooth">
        {/* <Hero homeInfo={homeInfo} /> */}
      </section>

      <section id="about" className="snap-center scroll-smooth">
        {/* <About aboutInfo={homeInfo} /> */}
      </section>

      <section id="experiences" className="snap-center scroll-smooth">
        <ExperienceComponent experiences={experiences} />
      </section>

      <section id="skills" className="snap-start scroll-smooth">
        {/* <Skills skills={skills} /> */}
      </section>

      <section id="projects" className="snap-start scroll-smooth">
        {/* <Projects projects={projects} /> */}
      </section>

      <section id="contact" className="snap-start scroll-smooth">
        <ContactMe />
      </section>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  // const homeInfo: HomeInfo = await fetchHomeInfo();

  // const socials: Social[] = await fetchSocials();
  // const projects: Project[] = await fetchProjects();
  // const skills: Skill[] = await fetchSkills();

  const query = groq`
*[_type == "experience"]{
    ...,
    technologies[]->
  }
`;

  type Data = {
    experiences: Experience[];
  };

  async function handler(req: NextApiRequest, res: NextApiResponse<Data>) {
    const experiences: Experience[] = await sanityClient.fetch(query);
    res.status(200).json({ experiences });
  }
  const fetchExperiences = async () => {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/getExperience`
    );

    const data = await res.json();
    const experiences: Experience[] = data.experiences;

    console.log("fetching", experiences);

    return experiences;
  };

  const experiences: Experience[] = await fetchExperiences();
  return {
    props: {
      // homeInfo,
      experiences,
      // skills,
      // socials,
      // projects,
    },

    //Next.js will attempt to re-generate the page:
    //- when a request comes in
    //- at most once every 10sec
    revalidate: 10,
  };
};
